### ISSUE TITLE
"Multiple modules match the path" assert triggered for common name prefix

### ISSUE THREAD

**Issue by allthesignals** [ember-learn/ember-cli-addon-docs#149] opened 2018-04-14 02:51 UTC
Our [addon](https://github.com/kturney/ember-mapbox-gl) namespaces modules with a prefix like this:

mapbox-gl
mapbox-gl-layer
mapbox-gl-call
etc...

Navigating to the generated `mapbox-gl` route throws:
Error:
> "Assertion Failed: multiple modules match the path 'components/mapbox-gl', ids: addon/components/mapbox-gl, addon/components/mapbox-gl-call, addon/components/mapbox-gl-control, addon/components/mapbox-gl-image, addon/components/mapbox-gl-layer, addon/components/mapbox-gl-marker, addon/components/mapbox-gl-on, addon/components/mapbox-gl-popup, addon/components/mapbox-gl-source"

[Source](https://github.com/ember-learn/ember-cli-addon-docs/blob/f032d9add87bd0084de580315e83f7292b4b7030/addon/routes/docs/api/item.js#L24)

Is there a workaround for this? Is matching done with regular expressions or exact match?

**Comment by allthesignals** [comment] 2018-04-14 16:10
Right now, I'm just overriding the route's model hook and removing the asserts, which is unsafe. Using a last path segment (`const lastPathSegment = path.split('/').pop();`) might work, but could create naming collisions because it strips out the path. 

The `file` property on the model is useful, but it includes a prefixed `/` so you can't use it as a lookup without some formatting. Not sure which solution path is going to break other scenarios...

**Comment by pzuraq** [comment] 2018-04-14 18:14
I think that logic is faulty, we should be able to match on exact matches I'm pretty sure. I need to think about why we didn't do that in the first place, but it seems broken. This is a duplicate of #94 so I'm going to close for now, we are tracking and will try to get a fix out soon

**Closed by pzuraq** 2018-04-14 18:14 UTC

**Comment by allthesignals** [comment] 2018-04-14 18:27
@pzuraq alright, I have a branch for this, can push up later and see what you think
