### ISSUE TITLE
Using latest version breaks previous working markdown files

### ISSUE THREAD

**Issue by josemarluedke** [ember-learn/ember-cli-addon-docs#402] opened 2019-09-06 23:09 UTC
I was using version `0.6.13` and then upgraded to `0.6.14` and my markdown files stopped working on inline code blocks. 

[Here is the markdown](https://gist.github.com/josemarluedke/c4828e7149fd273f7e2f85b19a14f365) we encountered the error. 

It seems that all the content after the code block in `Creating an Instance` got transformed into the code block itself, not rendering the remaining of the content.

**Comment by dfreeman** [comment] 2019-09-09 11:31
[This change](https://github.com/ember-learn/ember-cli-addon-docs/commit/900b09b4ada19a9c6d4f1d631871861127f48f47) seems likely to be your culprit. Off the cuff I'd guess that those regexps need to be multiline-aware to work with the snippet you linked, but the larger issue here is that we're trying to interleave two mostly-unrelated languages using tools that only know about one or the other.

I think we're likely to continue playing whack-a-mole with issues like this until someone cooks up a parser that's aware of both Markdown and Glimmer syntax and can handle their interplay. That sounds like the kind of project I could pretty easily get nerd-sniped by, but unfortunately I don't think I'll have the capacity to take it on any time soon 🙁

**Comment by mixonic** [comment] 2019-09-17 16:12
I've also seen this on a minor version bump with the error:

```
Closing tag `p` (on line 49) without an open tag.
```

When compiling [this file](https://github.com/Addepar/ember-table/blob/master/tests/dummy/app/pods/docs/guides/body/occlusion/template.md).

**Comment by Exelord** [comment] 2019-11-26 14:30
I also got into this issue. The problem is with using angle bracket components with no args. eg:
```
<My::Header>
  This will raise an error
</My::Header>
```

```
<My::Header @with="arg">
  This will work
</My::Header>
```

**Comment by bitwolfe** [comment] 2020-01-08 12:48
Any progress on this? Latest release (v0.6.16) still causes the `Closing tag `p` (on line 49) without an open tag.`. It seems to happen on all self-closing tags in combination with something as simple as having a capital letter anywhere in a tag, even in class names.

This doesn't work:

```hbs
{{#docs-demo as |demo|}}
  {{#demo.example name="example.hbs"}}
    <hr class="inputClass" />
  {{/demo.example}}

  {{demo.snippet "example.hbs"}}
{{/docs-demo}}
```

But this is fine:

```hbs
{{#docs-demo as |demo|}}
  {{#demo.example name="example.hbs"}}
    <hr class="input-class" />
  {{/demo.example}}

  {{demo.snippet "example.hbs"}}
{{/docs-demo}}
```

**Comment by bitwolfe** [comment] 2020-01-08 12:55
Also PR #413 does not fix the above issue.

**Closed** 2020-01-24 22:22 UTC
Labels: Bug

**Comment by rwwagner90** [comment] 2020-01-25 04:55
@samselikoff according to @bitwolfe that PR did not fix the issue?

**Comment by bitwolfe** [comment] 2020-09-10 09:16
This issue still exists with 0.10.0

**Comment by bitwolfe** [comment] 2020-09-10 09:46
I found a workaround for my issue at least, sharing here incase someone else runs into this. Adding a blank line at the beginning of the example block seems to fix my issue. So going with the same example as I used before:

This doesn't work:

```
{{#docs-demo as |demo|}}
  {{#demo.example name="example.hbs"}}
    <hr class="inputClass" />
  {{/demo.example}}

  {{demo.snippet "example.hbs"}}
{{/docs-demo}}
```

But this does!

```
{{#docs-demo as |demo|}}
  {{#demo.example name="example.hbs"}}

    <hr class="inputClass" />
  {{/demo.example}}

  {{demo.snippet "example.hbs"}}
{{/docs-demo}}
```

Super strange.

**Comment by rwwagner90** [comment] 2020-09-10 11:41
@bitwolfe we're using DocsDemo for ember-flatpickr and it seems to work fine for our use case. https://github.com/shipshapecode/ember-flatpickr/blob/master/tests/dummy/app/templates/docs/components/ember-flatpickr.md

I'm curious what the difference is or if it's just that we're using angle brackets? Would love to narrow down what doesn't work.

**Comment by bitwolfe** [comment] 2020-09-10 12:01
@rwwagner90 I've tested with angle brackets as well, that doesn't seem to matter.

The below also fails with the same error:

`Closing tag `p` (on line 5) did not match last open tag `DocsDemo` (on line 2).`

```
# Demo

<DocsDemo as |demo|>
  <demo.example @name="example.hbs">
    <hr class="fooBar"/>
  </demo.example>

  <demo.snippet @name="example.hbs"/>
</DocsDemo>
```

Again, adding a blank live before the hr tag magically makes it work.

**Comment by rwwagner90** [comment] 2020-09-10 14:06
@bitwolfe I wonder if it just has to be more than one line in general?

**Comment by bitwolfe** [comment] 2020-09-11 12:16
@rwwagner90 Unfortunately I don't think that's it, as I've had the same issue with multi-line examples as well. And today I was able to remove some blank lines that were required before. That may have to do with switching to angle brackets for the docs components though.

I seem to have found some sort of re-producible case however... And where the blank line is seems to matter greatly.

The following produces the `Closing tag` compiler error:

```
<DocsDemo as |demo|>
  <demo.example @name="ew-navbar.hbs">
    <EwNavbar as |nav|>
      <nav.Logo />
      <LinkTo @route="docs.index" class="ew-navbar-item">Home</LinkTo>
    </EwNavbar>
  </demo.example>

  <demo.snippet @name="ew-navbar.hbs"/>
</DocsDemo>
```

Adding a blank line before the component tag fixes the compiler error and the markdown following the example parses properly:

```
<DocsDemo as |demo|>
  <demo.example @name="ew-navbar.hbs">

    <EwNavbar as |nav|>
      <nav.Logo />
      <LinkTo @route="docs.index" class="ew-navbar-item">Home</LinkTo>
    </EwNavbar>
  </demo.example>

  <demo.snippet @name="ew-navbar.hbs"/>
</DocsDemo>
```

Moving the blank line inside the component tag breaks the markdown parsing again:

```
<DocsDemo as |demo|>
  <demo.example @name="ew-navbar.hbs">
    <EwNavbar as |nav|>

      <nav.Logo />
      <LinkTo @route="docs.index" class="ew-navbar-item">Home</LinkTo>
    </EwNavbar>
  </demo.example>

  <demo.snippet @name="ew-navbar.hbs"/>
</DocsDemo>
```

Moving the blank line down one more fixes the markdown parsing again:

```
<DocsDemo as |demo|>
  <demo.example @name="ew-navbar.hbs">
    <EwNavbar as |nav|>
      <nav.Logo />

      <LinkTo @route="docs.index" class="ew-navbar-item">Home</LinkTo>
    </EwNavbar>
  </demo.example>

  <demo.snippet @name="ew-navbar.hbs"/>
</DocsDemo>
```

If you move it down once more, things still work. But move it down after the component end-tag, and you once again get a compiler error. So it seems to be fine as long as you have a blank line in the right place.

**Comment by rwwagner90** [comment] 2020-09-11 15:37
@bitwolfe I really have no idea here. Seems like an off by one kind of thing I suppose. Any ideas how to debug?
