### ISSUE TITLE
CI is broken with projects using ember-cli-addon-docs

### ISSUE THREAD

**Issue by xcambar** [ember-learn/ember-cli-addon-docs#87] opened 2018-03-13 16:18 UTC
Syntax errors are declared starting with this file:

https://github.com/ember-learn/ember-cli-addon-docs/blob/master/lib/sandbox/app/components/esdoc-component.js

The syntax is obviously wrong, but I can't tell whether this was an intentional move, therefore I can't offer a PR or anything.

**Comment by xcambar** [comment] 2018-03-13 16:28
> The syntax is obviously wrong

I've called out by my colleague @GreatWizard for the syntax is not _wrong_, which is correct.

But it is incompatible for many(most? all?) users of the plugin, and then, maybe, it's just that some babel plugins are missing.

**Comment by dfreeman** [comment] 2018-03-13 16:31
@pzuraq I thought we weren't publishing anything in `lib/sandbox`?

**Comment by pzuraq** [comment] 2018-03-13 16:32
This is being caused by installing directly from the repo instead of from the NPM package, which the current docs say to do (should be fixed by #82). The published versions should have that sandbox ignored. I think this is problematic still, going to submit a fix which moves the folder and pulls it back in in `ember-cli-build` so there's no chance of this happening in installed apps.

**Comment by xcambar** [comment] 2018-03-13 16:50
That would be great.

FWIW, in the meantime we will resume working with a published version. Should anything go wrong, I will update here.

**Closed** 2018-03-13 21:20 UTC

**Comment by xcambar** [comment] 2018-03-14 06:16
Thanks!
